version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/typescript-boilerplate

    steps:
      - add_ssh_keys:
          fingerprints:
            - $CI_FINGERPRINT
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build doc folder
          command: npm run build
      - run:
          name: Deploy
          command: |
              git config --global push.default simple
              git pull
              git add .
              git push