version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: circleci/node:8
    working_directory: ~/typescript-boilerplate
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:4b:af:63:8a:86:a9:99:ec:5c:a8:4b:63:62:da:ba"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Deploy
          command: |
              git config --global push.default matching
              git pull
              npm run build
              git push