version: 2
jobs:
  build:
    branches:
        ignore:
            - gh-pages
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/typescript-boilerplate
    environment:
        - SOURCE_BRANCH: master
        - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "06:be:43:3f:6b:d7:7e:4b:1f:ef:f1:f5:de:49:20:e5"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build doc folder
          command: npm run build
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME

              git clone $CIRCLE_REPOSITORY_URL docs

              cd docs
              git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              npm run build

              cp -a build/. docs/.

              mkdir -p docs/.circleci && cp -a .circleci/. docs/.circleci/.
              cd docs

              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin $TARGET_BRANCH
            fi